<?php
/**
 * File: /admin/helpers.php
 * ---
 * Contains reusable helper functions for the admin panel.
 *
 * --- NEW (Phase 4) ---
 * - Added handle_image_upload() function.
 */

// We must include this for auth-check.php to work in item-action.php
require_once __DIR__ . '/../init.php';

/**
 * Handles a file upload, validates it, and moves it to the /uploads directory.
 *
 * @param string $file_input_name The 'name' attribute of the <input type="file">.
 * @param string $current_image_path The path of the image currently saved (from the hidden field).
 * @return string The path to the new file, or the $current_image_path if no new file was uploaded.
 */
function handle_image_upload($file_input_name, $current_image_path) {
    // Check if a new file was actually uploaded
    if (isset($_FILES[$file_input_name]) && $_FILES[$file_input_name]['error'] === UPLOAD_ERR_OK) {
        
        $file = $_FILES[$file_input_name];
        
        // --- Validation ---
        $allowed_types = ['image/jpeg', 'image/png', 'image/gif', 'image/jpg'];
        if (!in_array($file['type'], $allowed_types)) {
            // Not a valid image type. We could set an error message here.
            // For now, we just safely return the old path.
            return $current_image_path;
        }

        // --- Generate Safe, Unique Filename ---
        $file_extension = pathinfo($file['name'], PATHINFO_EXTENSION);
        $safe_filename = preg_replace('/[^a-z0-9_-]/i', '_', pathinfo($file['name'], PATHINFO_FILENAME));
        $new_filename = $safe_filename . '_' . time() . '.' . $file_extension;
        
        // --- Define Upload Path ---
        // __DIR__ is /admin, so we go up one, then into /uploads/
        $upload_dir = __DIR__ . '/../uploads/';
        $upload_path = $upload_dir . $new_filename;

        // --- Move the File ---
        if (move_uploaded_file($file['tmp_name'], $upload_path)) {
            // Success! Return the *public* path for the database.
            return '/uploads/' . $new_filename;
        } else {
            // Failed to move file (check permissions on /uploads/)
            return $current_image_path;
        }
    }
    
    // No new file was uploaded, so just return the existing path.
    return $current_image_path;
}


/**
 * Safely writes a PHP array to a .php file using var_export and file locking.
 *
 * @param string $filepath Full path to the target .php file.
 * @param string $variable_name The name of the variable to write (e.g., "destinations").
 * @param array $data_array The PHP array to save.
 * @return bool True on success, false on failure.
 */
function save_php_file($filepath, $variable_name, $data_array) {
    // Re-build the PHP file content
    $php_code = "<?php\n/**\n * This file is auto-generated by the Go Camp Admin Panel.\n * Do not edit this file manually.\n */\n\n";
    $php_code .= "\$" . $variable_name . " = " . var_export($data_array, true) . ";\n";

    // Use file locking (flock) to prevent race conditions
    $file_handle = fopen($filepath, 'w');
    if (!$file_handle) {
        return false; // Could not open file
    }

    // Get an exclusive lock
    if (flock($file_handle, LOCK_EX)) {
        fwrite($file_handle, $php_code); // Write the new content
        fflush($file_handle);            // Flush output before releasing lock
        flock($file_handle, LOCK_UN);    // Release the lock
    } else {
        fclose($file_handle);
        return false; // Could not get lock
    }

    fclose($file_handle);
    return true;
}

/**
 * Safely writes a PHP array to a .json file using json_encode and file locking.
 *
 * @param string $filepath Full path to the target .json file.
 * @param array $data_array The PHP array to save.
 * @return bool True on success, false on failure.
 */
function save_json_file($filepath, $data_array) {
    // Convert array to formatted JSON
    $json_string = json_encode($data_array, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

    // Use file locking (flock)
    $file_handle = fopen($filepath, 'w');
    if (!$file_handle) {
        return false; // Could not open file
    }

    // Get an exclusive lock
    if (flock($file_handle, LOCK_EX)) {
        fwrite($file_handle, $json_string); // Write the new content
        fflush($file_handle);               // Flush output before releasing lock
        flock($file_handle, LOCK_UN);       // Release the lock
    } else {
        fclose($file_handle);
        return false; // Could not get lock
    }

    fclose($file_handle);
    return true;
}

/**
 * Generates a unique slug for a new item (e.g., "italy-copy-1", "italy-copy-2").
 *
 * @param string $base_slug The starting slug (e.g., "italy-copy").
 * @param array $existing_keys The array of existing slugs to check against.
 * @return string A unique slug.
 */
function generate_unique_slug($base_slug, $existing_keys) {
    if (!in_array($base_slug, $existing_keys)) {
        return $base_slug;
    }

    $counter = 1;
    while (in_array($base_slug . '-' . $counter, $existing_keys)) {
        $counter++;
    }
    return $base_slug . '-' . $counter;
}
?>