<?php
/**
 * This file is auto-generated by the Go Camp Admin Panel.
 * Do not edit this file manually.
 */

$all_programs = array (
    // ADULT ACADEMIC (1-2)
    'germany-university-pathway' => array (
        'order' => 1,
        'id' => 'germany-university-pathway',
        'category_slug' => 'adult-academic',
        'name' => 'University Pathway',
        'image' => '/images/germ_1.jpg',
        'ages' => 
        array (
            'min' => 17,
            'max' => 99,
        ),
        'duration' => 12,
        'price' => '€8,000',
        'color' => 'secondary',
        'badges' => 
        array (
            0 => 'Academic',
            1 => 'Year-Round',
        ),
        'highlights' => 
        array (
            0 => 'Prepare for university entry',
            1 => 'Studienkolleg prep course',
            2 => 'TestDaf prep',
            3 => 'Guidance through every step',
        ),
        'description' => 'This program guides you through every step to university, including language preparation and entrance exam courses.',
        'status' => 'inactive', // Set to inactive
    ),
    'usa-pre-university' => 
    array (
        'order' => 2,
        'id' => 'usa-pre-university',
        'category_slug' => 'adult-academic',
        'name' => 'Pre-University Camp',
        'image' => '/images/usa_3.jpg',
        'ages' => 
        array (
            'min' => 16,
            'max' => 18,
        ),
        'duration' => 4,
        'price' => '$5,200',
        'color' => 'primary',
        'badges' => 
        array (
            0 => 'Academic',
            1 => 'University Prep',
        ),
        'highlights' => 
        array (
            0 => 'Experience university life',
            1 => 'SAT/ACT prep sessions',
            2 => 'College application workshops',
            3 => 'Campus tours in Boston or LA',
        ),
        'description' => 'Get a head start on your university applications and experience life on a US college campus.',
        'status' => 'inactive', // Set to inactive
    ),
    // KIDS CAMPS (1-3)
    // 'italy-junior-discover' => 
    // array (
    //     'order' => 1,
    //     'id' => 'italy-junior-discover',
    //     'category_slug' => 'kids-camps',
    //     'name' => 'Junior Discover',
    //     'tagline' => 'An exciting full-immersion experience for young adventurers',
    //     'image' => '/images/italy_1.jpg',
    //     'ages' => 
    //     array (
    //         'min' => '6',
    //         'max' => '12',
    //     ),
    //     'duration' => 2,
    //     'level' => 'Beginner',
    //     'price' => '€2,400',
    //     'color' => 'accent',
    //     'badges' => 
    //     array (
    //         0 => 'Popular',
    //         1 => 'Hot',
    //     ),
    //     'highlights' => 
    //     array (
    //         0 => 'Daily sports & team competitions',
    //         1 => 'Theatre & creative arts workshops',
    //         2 => 'Treasure hunts & adventure games',
    //         3 => 'Full board accommodation',
    //     ),
    //     'description' => '<p>Children participate in an exciting and educational full-immersion experience designed to foster creativity, teamwork, and personal growth. This program combines physical activities with cultural exploration in a safe, supervised environment.</p>',
    //     'schedule' => 
    //     array (
    //         '7:30 AM' => 'Wake up & breakfast',
    //         '9:00 AM' => 'Morning sports activities',
    //         '12:30 PM' => 'Lunch & rest time',
    //         '2:30 PM' => 'Afternoon workshops',
    //         '7:00 PM' => 'Dinner & Evening activities',
    //     ),
    //     'includes' => 
    //     array (
    //         0 => 'All meals & snacks',
    //         1 => 'Accommodation',
    //         2 => 'All activities and equipment',
    //         3 => 'Medical insurance',
    //         4 => 'Airport transfers',
    //     ),
    //     'excludes' => 
    //     array (
    //         0 => 'International flights',
    //         1 => 'Personal spending money',
    //         2 => 'Visa fees',
    //     ),
    //     'status' => 'active',
    // ),
    'italy-junior-discovery' => array(
        'order' => 2,
        'id' => 'italy-junior-discovery',
        'category_slug' => 'kids-camps',
        'name' => 'Junior Discovery',
        'tagline' => 'Empowering students to explore their potential through experiential education and blending culture, and adventure.',
        'image' => '',
        'ages' => array('min' => 12, 'max' => 16),
        'duration' => null,
        'level' => null,
        'price' => null,
        'color' => 'success',
            'badges' => array('New', 'Explorer'),
        'highlights' => array(
            0 => 'Empowering students to explore their potential through experiential education.',
            1 => 'Innovative summer programs blending education, culture, and adventure.',
            2 => 'Camp is entirely conducted in English.',
            3 => 'Develop independence, form new friendships, strengthen communication skills, and learn the value of teamwork.'
        ),
        'description' => '<p>Junior Discovery Camp offers innovative summer programs in the heart of Italy. These camps provide a comprehensive learning environment where students can explore their potential.</p>',
        'includes' => array(),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'germany-children-summer' => 
    array (
        'order' => 3,
        'id' => 'germany-children-summer',
        'category_slug' => 'kids-camps',
        'name' => 'Children Summer Camps',
        'image' => '/images/germany_2.jpg',
        'ages' => 
        array (
            'min' => 8,
            'max' => 14,
        ),
        'duration' => 2,
        'price' => '€2,200',
        'color' => 'primary',
        'badges' => 
        array (
            0 => 'Language',
            1 => 'Summer',
        ),
        'highlights' => 
        array (
            0 => 'Intensive German lessons',
            1 => 'Afternoon activities',
            2 => 'Cultural excursions',
            3 => 'Safe, supervised environment',
        ),
        'description' => 'A fun and effective way for children to learn German while exploring the culture and making international friends.',
        'status' => 'inactive', // Set to inactive
    ),
    // LANGUAGE AND ACTIVITY CAMPS (1-2)
    'spain-language-water-sports' => 
    array (
        'order' => 1,
        'id' => 'spain-language-water-sports',
        'category_slug' => 'language-and-activity-camps',
        'name' => 'Language & Water Sports',
        'image' => '/images/spain_1_g.jpg',
        'ages' => 
        array (
            'min' => 10,
            'max' => 17,
        ),
        'duration' => 2,
        'price' => '€2,600',
        'color' => 'secondary',
        'badges' => 
        array (
            0 => 'Popular',
            1 => 'Summer',
        ),
        'highlights' => 
        array (
            0 => 'Spanish or English classes',
            1 => 'Sailing & Windsurfing',
            2 => 'Paddle Surfing & Kayaking',
            3 => 'Beach activities',
        ),
        'description' => 'Combine language learning with exciting water sports on the beautiful Spanish coast.',
        'status' => 'inactive', // Set to inactive
    ),
    'canada-english-ski' => 
    array (
        'order' => 2,
        'id' => 'canada-english-ski',
        'category_slug' => 'language-and-activity-camps',
        'name' => 'English & Ski (Winter)',
        'image' => '/images/canada_3.jpg',
        'ages' => 
        array (
            'min' => 13,
            'max' => 18,
        ),
        'duration' => 2,
        'price' => '$4,100',
        'color' => 'primary',
        'badges' => 
        array (
            0 => 'Winter',
            1 => 'Sports',
            2 => 'Language',
        ),
        'highlights' => 
        array (
            0 => 'Morning English classes',
            1 => 'Afternoon skiing/snowboarding',
            2 => 'Located in Whistler',
            3 => 'All equipment provided',
        ),
        'description' => 'Improve your English and your skiing or snowboarding skills in the world-renowned resort of Whistler.',
        'status' => 'inactive', // Set to inactive
    ),
    // SOCCER CAMPS (1-2)
    'italy-football-ac-milan' => array(
        'order' => 1,
        'id' => 'italy-football-ac-milan',
        'category_slug' => 'soccer-camps',
        'name' => 'Football with AC Milan',
        'tagline' => 'Unparalleled football training under the guidance of AC Milan’s Youth Team and Academy coaches.',
        'image' => '',
        'ages' => array('min' => 8, 'max' => 16),
        'duration' => null,
        'level' => null,
        'price' => null,
        'color' => 'danger',
        'badges' => array('Official'),
        'highlights' => array(
            0 => 'Unparalleled football training with AC Milan’s Youth Team coaches and official Milan Academy coaches.',
            1 => 'Tournaments & Friendly games.',
            2 => 'Specialized training for players who are goalkeepers.'
        ),
        'description' => '<p>This program offers unparalleled football training for boys and girls aged 8 to 16. Training is conducted under the guidance of AC Milan’s Youth Team coaches and official Milan Academy coaches.</p>',
        'includes' => array(
            'Individual football coaching',
            'Recordings on camera',
            'Performance certificate',
            'AC Milan’s official kit',
            'FB Accommodations',
            'Special camp excursions'
        ),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'spain-soccer-camp' => 
    array (
        'order' => 2,
        'id' => 'spain-soccer-camp',
        'category_slug' => 'soccer-camps',
        'name' => 'Pro Soccer Camp',
        'image' => '/images/spain_4_g.jpg',
        'ages' => 
        array (
            'min' => 8,
            'max' => 18,
        ),
        'duration' => 2,
        'price' => '€3,100',
        'color' => 'primary',
        'badges' => 
        array (
            0 => 'Sports',
            1 => 'Popular',
        ),
        'highlights' => 
        array (
            0 => 'Train with top coaches',
            1 => 'Improve technical skills',
            2 => 'Tactical workshops',
            3 => 'Visit famous stadiums',
        ),
        'description' => 'For the soccer fans of FC Barcelona or Real Madrid, this camp offers professional training and an unforgettable experience.',
        'status' => 'inactive', // Set to inactive
    ),
    // SPECIAL INTERESTS CAMPS (1-7)
    'switzerland-adventure-camp' => 
    array (
        'order' => 1,
        'id' => 'switzerland-adventure-camp',
        'category_slug' => 'special-interests-camps',
        'name' => 'Adventure Camp',
        'image' => '/images/swiss_2.jpg',
        'ages' => 
        array (
            'min' => 10,
            'max' => 16,
        ),
        'duration' => 2,
        'price' => '€3,500',
        'color' => 'secondary',
        'badges' => 
        array (
            0 => 'Adventure',
            1 => 'Popular',
        ),
        'highlights' => 
        array (
            0 => 'Mountain hiking',
            1 => 'Lake activities',
            2 => 'Chocolate & cheese tasting',
            3 => 'Team building',
        ),
        'description' => 'A classic summer camp experience in the Swiss Alps, focusing on outdoor adventure and making new friends.',
        'status' => 'inactive', // Set to inactive
    ),
    'canada-adventure-summer' => 
    array (
        'order' => 2,
        'id' => 'canada-adventure-summer',
        'category_slug' => 'special-interests-camps',
        'name' => 'Adventure Summer Camp',
        'image' => '/images/canada_2.jpg',
        'ages' => 
        array (
            'min' => 12,
            'max' => 17,
        ),
        'duration' => 2,
        'price' => '$3,800',
        'color' => 'secondary',
        'badges' => 
        array (
            0 => 'Adventure',
            1 => 'Summer',
        ),
        'highlights' => 
        array (
            0 => 'Canoeing in pristine lakes',
            1 => 'Hiking in national parks',
            2 => 'Wildlife spotting',
            3 => 'Campfire stories',
        ),
        'description' => 'Explore the great Canadian outdoors with our adventure summer camp, based in beautiful British Columbia.',
        'status' => 'inactive', // Set to inactive
    ),
    'italy-fashion' => array(
        'order' => 3,
        'id' => 'italy-fashion',
        'category_slug' => 'special-interests-camps',
        'name' => 'Fashion',
        'tagline' => 'Immerse yourself in the world of fashion design in the heart of Milan.',
        'image' => '',
        'ages' => array('min' => 15, 'max' => 18),
        'duration' => null,
        'level' => null,
        'price' => null,
        'color' => 'secondary',
            'badges' => array('New', 'Design'),
        'highlights' => array(
            0 => 'Introduction to product design and brainstorming for innovative ideas.',
            1 => 'Use of AI software to develop unique product concepts.',
            2 => 'Learn graphic design techniques for detailed sketches.',
            3 => 'Culmination with prototyping, transforming digital ideas into tangible creation.'
        ),
        'description' => '<p>The Program in Fashion is perfect for young fashion enthusiasts who want to immerse themselves in the world of fashion design. Held in the heart of Milan, participants will have the chance to explore, develop, and showcase their creativity. It is ideal for those aspiring to enter the fashion industry and eager to explore various aspects of the fashion field.</p>',
        'includes' => array(),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'switzerland-film-academy' => 
    array (
        'order' => 4,
        'id' => 'switzerland-film-academy',
        'category_slug' => 'special-interests-camps',
        'name' => 'Film Academy Camp',
        'image' => '/images/swiss_4.jpg',
        'ages' => 
        array (
            'min' => 14,
            'max' => 18,
        ),
        'duration' => 3,
        'price' => '€4,200',
        'color' => 'accent',
        'badges' => 
        array (
            0 => 'Creative',
            1 => 'Specialty',
        ),
        'highlights' => 
        array (
            0 => 'Screenwriting',
            1 => 'Directing',
            2 => 'Cinematography',
            3 => 'Editing with pro software',
        ),
        'description' => 'A hands-on camp for aspiring filmmakers. Write, shoot, and edit your own short film in a stunning location.',
        'status' => 'inactive', // Set to inactive
    ),
    'italy-food' => array(
        'order' => 5,
        'id' => 'italy-food',
        'category_slug' => 'special-interests-camps',
        'name' => 'Food',
        'tagline' => 'Hands-on experience in Italian cooking, baking, and pastry making, in partnership with IN CONGUSTO INSTITUTE.',
        'image' => '',
        'ages' => array('min' => 15, 'max' => 18),
        'duration' => 'Intensive 40-hour programme',
        'level' => null,
        'price' => null,
        'color' => 'info',
            'badges' => array('Partnership', 'Culinary Arts'),
        'highlights' => array(
            0 => 'Partnership with IN CONGUSTO INSTITUTE.',
            1 => 'Intensive 40-hour programme.',
            2 => 'Hands-on experience in Italian cooking, baking, and pastry making.',
            3 => 'Exploration of the restaurant business and new culinary formats.'
        ),
        'description' => '<p>The Italian Gastronomic Arts Summer Campus offers participants hands-on experience in Italian cooking, baking, and pastry making. The program also explores the restaurant business and new culinary formats, making it ideal for students aspiring to access careers in the food industry.</p>',
        'includes' => array(
            'Practical and theoretical lessons',
            'Equipment and ingredients',
            'Field trips & excursions',
            'Supplementary activities',
            'Special events',
            'Accommodation',
            'Milan sightseeing',
            'Visit to cheese factory'
        ),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'italy-outdoor-exploration' => 
    array (
        'order' => 6,
        'id' => 'italy-outdoor-exploration',
        'category_slug' => 'special-interests-camps',
        'name' => 'Outdoor Exploration',
        'tagline' => 'Challenge yourself with thrilling outdoor adventures',
        'image' => '/images/italy_2.jpg',
        'ages' => 
        array (
            'min' => 12,
            'max' => 16,
        ),
        'duration' => 3,
        'level' => 'Intermediate',
        'price' => '€3,200',
        'color' => 'secondary',
            'badges' => 
            array (
                0 => 'Adventure',
                1 => 'Challenge',
            ),
        'highlights' => 
        array (
            0 => 'Rock climbing',
            1 => 'Whitewater rafting',
            2 => 'Mountain biking',
            3 => 'Orienteering and navigation skills',
        ),
        'description' => '<p>Every day campers will face a new outdoor activity, representing for most a totally new challenge. This program is designed for teenagers seeking adventure and personal growth through outdoor activities.</p>',
        'schedule' => 
        array (
            '7:00 AM' => 'Breakfast & briefing',
            '8:00 AM' => 'Morning adventure activity',
            '12:30 PM' => 'Lunch (on location)',
            '2:00 PM' => 'Afternoon expedition',
            '7:30 PM' => 'Dinner & debrief',
        ),
        'includes' => 
        array (
            0 => 'All outdoor equipment',
            1 => 'Professional guides',
            2 => 'Accommodation in lodges',
            3 => 'All meals',
            4 => 'Safety equipment',
        ),
        'excludes' => 
        array (
            0 => 'International flights',
            1 => 'Personal outdoor gear',
            2 => 'Spending money',
        ),
        'status' => 'active', // Maintained active
    ),
    'italy-sea-quest' => 
    array (
        'order' => 7,
        'id' => 'italy-sea-quest',
        'category_slug' => 'special-interests-camps',
        'name' => 'Sea Quest',
        'tagline' => 'Two-week sailing expedition along Italy\'s stunning coastline',
        'image' => '/images/italy_3.jpg',
        'ages' => 
        array (
            'min' => 14,
            'max' => 17,
        ),
        'duration' => 2,
        'level' => 'Advanced',
        'price' => '€3,800',
        'color' => 'accent',
        'badges' => 
        array (
            0 => 'Premium',
            1 => 'Limited',
        ),
        'highlights' => 
        array (
            0 => 'Sail around famous islands',
            1 => 'Learn core nautical skills',
            2 => 'Coastal exploration',
            3 => 'Onboard living experience',
        ),
        'description' => '<p>Sea Quest is a two-week sailing expedition around the most beautiful and famous islands of the Italian coast. This program introduces the magic of sailing and core nautical skills while voyaging along one of the Mediterranean\'s most idyllic coastlines.</p>',
        'schedule' => 
        array (
            '8:00 AM' => 'Sailing instruction & navigation',
            '10:00 AM' => 'Set sail',
            '1:00 PM' => 'Lunch & swimming stop',
            '3:00 PM' => 'Afternoon sailing',
            '7:30 PM' => 'Dinner & shore exploration',
        ),
        'includes' => 
        array (
            0 => 'Private yacht with crew',
            1 => 'All sailing instruction',
            2 => 'All meals onboard',
            3 => 'Snorkeling equipment',
            4 => 'Safety gear',
        ),
        'excludes' => 
        array (
            0 => 'International flights',
            1 => 'Shore meals (optional)',
            2 => 'Personal sailing gear',
        ),
        'status' => 'active', // Maintained active
    ),
    // SPORTS CAMPS (1-3)
    'italy-tennis' => array(
        'order' => 1,
        'id' => 'italy-tennis',
        'category_slug' => 'sports-camps',
        'name' => 'Tennis',
        'tagline' => 'High-Performance Junior Tennis Camp for elite training in an iconic Italian destination.',
        'image' => '',
        'ages' => array('min' => null, 'max' => null),
        'duration' => null,
        'level' => 'High-Performance',
        'price' => null,
        'color' => 'warning',
        'badges' => array('Elite'),
        'highlights' => array(
            0 => 'High-level sports training with an educational and stimulating environment.',
            1 => 'Elite training in one of Italy’s most iconic tennis destinations.',
            2 => 'Develop your game on state-of-the-art courts.',
            3 => 'Internal tournaments, and friendly matches.'
        ),
        'description' => '<p>The High-Performance Junior Tennis Camp is perfect for young tennis players who want to experience elite training and ensures a stimulating environment, guaranteeing young athletes concrete tools for their growth. Participants will develop their game where professional players and national teams have prepared for international success.</p>',
        'includes' => array(
            'Individual tennis coaching',
            '30 hours of tennis coaching with experienced coaches',
            'Mental game and tactical workshop',
            'Recordings on camera',
            'Performance certificate',
            'Full board accommodation',
            'Closing award ceremony'
        ),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'italy-sailing' => array(
        'order' => 2,
        'id' => 'italy-sailing',
        'category_slug' => 'sports-camps',
        'name' => 'Sailing',
        'tagline' => 'A thrilling sailing voyage exploring the stunning islands off Italy’s coast for core nautical skills and teamwork.',
        'image' => '',
        'ages' => array('min' => 12, 'max' => 16),
        'duration' => null,
        'level' => null,
        'price' => null,
        'color' => 'primary',
        'badges' => array('Adventure'),
        'highlights' => array(
            0 => 'Extraordinary sailing adventure exploring the stunning islands off Italy’s coast.',
            1 => 'Campers learn core nautical skills and experience life aboard 50-foot yachts.',
            2 => 'Sail as part of a three-yacht flotilla, guided by experienced instructors.',
            3 => 'Participate in interactive lessons on marine life and local history.'
        ),
        'description' => '<p>A thrilling sailing voyage enriched with local knowledge and new horizons for 12 to 16-year-olds. Campers navigate the Mediterranean’s bluest waters while growing as a team. British RYA instructors and native English-speaking counselors lead the entire program in English. Through hands-on learning, campers learn sailing techniques, teamwork, and leadership, building communication skills and self-reliance. Students earn a sailing certificate of achievement.</p>',
        'includes' => array(),
        'excludes' => array(),
        'status' => 'active', // Maintained active
    ),
    'switzerland-ski-camp' => 
    array (
        'order' => 3,
        'id' => 'switzerland-ski-camp',
        'category_slug' => 'special-interests-camps',
        'name' => 'Ski Camp (Winter)',
        'image' => '/images/swiss_3.jpg',
        'ages' => 
        array (
            'min' => 8,
            'max' => 17,
        ),
        'duration' => 1,
        'price' => '€2,800',
        'color' => 'primary',
        'badges' => 
        array (
            0 => 'Winter',
            1 => 'Sports',
        ),
        'highlights' => 
        array (
            0 => 'Professional ski instruction',
            1 => 'Access to top resorts',
            2 => 'Après-ski activities',
            3 => 'All gear included',
        ),
        'description' => 'Learn to ski or improve your skills on world-famous Swiss slopes with professional instructors.',
        'status' => 'inactive', // Set to inactive
    ),
    // YOUNG LEADER PROGRAM (1)
    'usa-global-leadership' => 
    array (
        'order' => 1,
        'id' => 'usa-global-leadership',
        'category_slug' => 'young-leader-program',
        'name' => 'Global Leadership Training',
        'image' => '/images/usa_2.jpg',
        'ages' => 
        array (
            'min' => 15,
            'max' => 18,
        ),
        'duration' => 3,
        'price' => '$4,500',
        'color' => 'accent',
        'badges' => 
        array (
            0 => 'Leadership',
            1 => 'Academic',
        ),
        'highlights' => 
        array (
            0 => 'Public speaking workshops',
            1 => 'Debate and negotiation',
            2 => 'Project management',
            3 => 'Visits to major organizations',
        ),
        'description' => 'Develop the skills to become a future leader in a globalized world, with workshops and real-world case studies.',
        'status' => 'inactive', // Set to inactive
    ),
);

?>