<?php
/**
 * This file is auto-generated by the Go Camp Admin Panel.
 * Do not edit this file manually.
 */

$destinations = array (
  'italy' => 
  array (
    'name' => 'Italy',
    'slug' => 'italy',
    'status' => 'active',
    'banner' => '/images/it_banner_new.jpg',
    'tagline' => '',
    'intro_image' => '/images/it_inn_banner.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">Italy offers the perfect blend of outdoor adventure, cultural enrichment, and unforgettable experiences. Our programs are designed to challenge, inspire, and create lifelong memories.</p>',
    'highlights' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'gallery' => 
    array (
    ),
    'faq' => 
    array (
    ),
    'program_ids' => 
    array (
      0 => 'italy-junior-discovery',
      1 => 'italy-football-ac-milan',
      2 => 'italy-fashion',
      3 => 'italy-food',
      4 => 'italy-outdoor-exploration',
      5 => 'italy-tennis',
      6 => 'italy-sailing',
    ),
  ),
  'switzerland' => 
  array (
    'name' => 'Switzerland',
    'slug' => 'switzerland',
    'status' => 'active',
    'banner' => '/images/swiss_banner.jpg',
    'tagline' => '',
    'intro_image' => '/images/swiss_1.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">Enjoy high-quality Swiss facilities, pure mountain air, and a natural environment of meadows, forests, and wildlife. Highlights include hikes to taste homemade <strong>cheese and chocolate</strong>.</p>',
    'highlights' => 
    array (
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
      0 => 'switzerland-adventure-camp',
      1 => 'switzerland-film-academy',
      2 => 'switzerland-ski-camp',
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
  'germany' => 
  array (
    'name' => 'Germany',
    'slug' => 'germany',
    'status' => 'coming-soon',
    'banner' => '/images/germany_banner.jpg',
    'tagline' => 'Language, Academia, and Culture',
    'intro_image' => '/images/germany_1.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">The best way to learn German is through full immersion in one of our many schools and summer centers across Germany. We also offer university pathway programs for higher education.</p>',
    'highlights' => 
    array (
      0 => 
      array (
        'icon' => 'translate',
        'text' => 'Full Language Immersion',
      ),
      1 => 
      array (
        'icon' => 'building-fill',
        'text' => 'University Pathway',
      ),
      2 => 
      array (
        'icon' => 'briefcase-fill',
        'text' => 'Executive & Pro Courses',
      ),
      3 => 
      array (
        'icon' => 'people-fill',
        'text' => 'Junior & Adult Programs',
      ),
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
  'spain' => 
  array (
    'name' => 'Spain',
    'slug' => 'spain',
    'status' => 'coming-soon',
    'banner' => '/images/spainr_banner_new.jpg',
    'tagline' => 'Sun, Language, and Soccer',
    'intro_image' => '/images/spain_22.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">Spain is a perfect destination for our summer camps, where students can learn Spanish or English combined with activities like water sports and world-class soccer training.</p>',
    'highlights' => 
    array (
      0 => 
      array (
        'icon' => 'translate',
        'text' => 'Spanish/English Lessons',
      ),
      1 => 
      array (
        'icon' => 'water',
        'text' => 'Water Sports',
      ),
      2 => 
      array (
        'icon' => 'dribbble',
        'text' => 'Pro Soccer Camps',
      ),
      3 => 
      array (
        'icon' => 'geo-alt-fill',
        'text' => 'Multiple Locations',
      ),
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
  'usa' => 
  array (
    'name' => 'USA & Canada',
    'slug' => 'usa',
    'status' => 'coming-soon',
    'banner' => '/images/usa_banner.jpg',
    'tagline' => 'Diverse Camps from Coast to Coast',
    'intro_image' => '/images/usa_1.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">The USA offers a vast array of programs catering to every interest, from academics and technology to sports and the arts in iconic cities.</p>',
    'highlights' => 
    array (
      0 => 
      array (
        'icon' => 'building',
        'text' => 'Camps in Major Cities',
      ),
      1 => 
      array (
        'icon' => 'lightbulb-fill',
        'text' => 'Leadership Programs',
      ),
      2 => 
      array (
        'icon' => 'mortarboard-fill',
        'text' => 'Pre-University Prep',
      ),
      3 => 
      array (
        'icon' => 'person-wheelchair',
        'text' => 'Special Needs Camps',
      ),
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
  'canada' => 
  array (
    'name' => 'Canada',
    'slug' => 'canada',
    'status' => 'trash',
    'banner' => '/images/canada_banner.jpg',
    'tagline' => 'Urban Excitement & Natural Wonders',
    'intro_image' => '/images/canada_1.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">Canada offers a unique blend of urban excitement and breathtaking natural landscapes. Our programs provide an incredible opportunity to learn new skills and enjoy thrilling adventures.</p>',
    'highlights' => 
    array (
      0 => 
      array (
        'icon' => 'tree-fill',
        'text' => 'Outdoor Adventures',
      ),
      1 => 
      array (
        'icon' => 'snow',
        'text' => 'English & Ski Camps',
      ),
      2 => 
      array (
        'icon' => 'globe',
        'text' => 'Young World Leaders',
      ),
      3 => 
      array (
        'icon' => 'book-fill',
        'text' => 'IELTS/FCE Prep',
      ),
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
  'uk' => 
  array (
    'name' => 'United Kingdom',
    'slug' => 'uk',
    'status' => 'trash',
    'banner' => '',
    'tagline' => '',
    'intro_image' => '',
    'intro_text' => '<p class="lead text-muted mb-4">Live, learn, and connect in one of the world&rsquo;s most inspiring academic cities.</p>',
    'highlights' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'gallery' => 
    array (
    ),
    'faq' => 
    array (
    ),
    'program_ids' => 
    array (
      0 => 'uk-young-professional',
      1 => 'uk-pre-university',
      2 => 'uk-english-foundation',
    ),
  ),
  'france' => 
  array (
    'name' => 'France',
    'slug' => 'france',
    'status' => 'coming-soon',
    'banner' => '/images/france_banner.jpg',
    'tagline' => 'Culture, Language, and Art de Vivre',
    'intro_image' => '/images/france_banner.jpg',
    'intro_text' => '<p class="lead text-muted mb-4">Information about our exciting new programs in France is coming soon. Please contact us for more details.</p>',
    'highlights' => 
    array (
      0 => 
      array (
        'icon' => 'palette-fill',
        'text' => 'Art & Culture',
      ),
      1 => 
      array (
        'icon' => 'translate',
        'text' => 'French Immersion',
      ),
      2 => 
      array (
        'icon' => 'cup-hot-fill',
        'text' => 'Culinary Experiences',
      ),
      3 => 
      array (
        'icon' => 'building',
        'text' => 'Historic Locations',
      ),
    ),
    'gallery' => 
    array (
    ),
    'program_ids' => 
    array (
    ),
    'stats' => 
    array (
    ),
    'faq' => 
    array (
    ),
  ),
);
